name: Checks
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Run tests
      run: bun run test
    - name: Report status
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          github.rest.checks.create({
            ...context.repo,
            name: 'tests',
            head_sha: context.sha,
            status: 'completed',
            conclusion: '${{ job.status }}'.toLowerCase(),
          });
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Validate types
      run: bun run type-check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Lint
      run: bun run lint